# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: 'Welcome'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    packageApp: false
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true
    publishJUnitResults: true
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Welcome'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
